name: Github Actions Exercise
on: [push]
jobs:
  clone:
    name: Clone repo and print content of test-file
    runs-on: [ubuntu-latest]
    steps:
    - name: checkout repo
      uses: actions/checkout@v4.2.2
    - name: print the content of test-file
      run: |
        cat test-file
  print:
    name: Print current date
    runs-on: [ubuntu-latest]
    needs: [clone]
    steps:
    - name: print current date
      run: date
